image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - yarn
  - npx puppeteer browsers install chrome@latest

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn run build   # команда сборки
  - sleep 10 

test_script:
  - echo "Running lint..."
  - yarn run lint
  - echo "Running E2E tests..."
  - yarn run start &  # Запускаем веб-сервер в фоновом режиме
  - sleep 10  # Ждем несколько секунд, чтобы веб-сервер успел стартовать
  - yarn run e2e

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose